/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMinter } from "../IMinter";

export class IMinter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMinter {
    return new Contract(address, _abi, signerOrProvider) as IMinter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_collateralAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_numTokens",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_collateralAddress",
        type: "address",
      },
    ],
    name: "depositByCollateralAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_collateralAddress",
        type: "address",
      },
    ],
    name: "getTotalCollateralByCollateralAddress",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "address",
        name: "_collateralAddress",
        type: "address",
      },
    ],
    name: "getUserCollateralByCollateralAddress",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_collateralAddress",
        type: "address",
      },
    ],
    name: "redeemByCollateralAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
