/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IMinterInterface extends ethers.utils.Interface {
  functions: {
    "depositByCollateralAddress(uint256,uint256,address)": FunctionFragment;
    "getTotalCollateralByCollateralAddress(address)": FunctionFragment;
    "getUserCollateralByCollateralAddress(address,address)": FunctionFragment;
    "redeemByCollateralAddress(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositByCollateralAddress",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCollateralByCollateralAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCollateralByCollateralAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemByCollateralAddress",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositByCollateralAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCollateralByCollateralAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCollateralByCollateralAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemByCollateralAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMinter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IMinterInterface;

  functions: {
    depositByCollateralAddress(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositByCollateralAddress(uint256,uint256,address)"(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTotalCollateralByCollateralAddress(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getTotalCollateralByCollateralAddress(address)"(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserCollateralByCollateralAddress(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getUserCollateralByCollateralAddress(address,address)"(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    redeemByCollateralAddress(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "redeemByCollateralAddress(uint256,address)"(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositByCollateralAddress(
    _collateralAmount: BigNumberish,
    _numTokens: BigNumberish,
    _collateralAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositByCollateralAddress(uint256,uint256,address)"(
    _collateralAmount: BigNumberish,
    _numTokens: BigNumberish,
    _collateralAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTotalCollateralByCollateralAddress(
    _collateralAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalCollateralByCollateralAddress(address)"(
    _collateralAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserCollateralByCollateralAddress(
    _user: string,
    _collateralAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getUserCollateralByCollateralAddress(address,address)"(
    _user: string,
    _collateralAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  redeemByCollateralAddress(
    _tokenAmount: BigNumberish,
    _collateralAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "redeemByCollateralAddress(uint256,address)"(
    _tokenAmount: BigNumberish,
    _collateralAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositByCollateralAddress(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositByCollateralAddress(uint256,uint256,address)"(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getTotalCollateralByCollateralAddress(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalCollateralByCollateralAddress(address)"(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserCollateralByCollateralAddress(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserCollateralByCollateralAddress(address,address)"(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemByCollateralAddress(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "redeemByCollateralAddress(uint256,address)"(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    depositByCollateralAddress(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositByCollateralAddress(uint256,uint256,address)"(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTotalCollateralByCollateralAddress(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalCollateralByCollateralAddress(address)"(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserCollateralByCollateralAddress(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserCollateralByCollateralAddress(address,address)"(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemByCollateralAddress(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "redeemByCollateralAddress(uint256,address)"(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositByCollateralAddress(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositByCollateralAddress(uint256,uint256,address)"(
      _collateralAmount: BigNumberish,
      _numTokens: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTotalCollateralByCollateralAddress(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalCollateralByCollateralAddress(address)"(
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserCollateralByCollateralAddress(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserCollateralByCollateralAddress(address,address)"(
      _user: string,
      _collateralAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemByCollateralAddress(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "redeemByCollateralAddress(uint256,address)"(
      _tokenAmount: BigNumberish,
      _collateralAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
