/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RecalculateRewardsPerBlockTestInterface
  extends ethers.utils.Interface {
  functions: {
    "recalculateRewardPerBlockTest(uint256,uint256,uint256)": FunctionFragment;
    "recalculateRewardUsingEpochRewardAmountTest(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "recalculateRewardPerBlockTest",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recalculateRewardUsingEpochRewardAmountTest",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "recalculateRewardPerBlockTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recalculateRewardUsingEpochRewardAmountTest",
    data: BytesLike
  ): Result;

  events: {};
}

export class RecalculateRewardsPerBlockTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RecalculateRewardsPerBlockTestInterface;

  functions: {
    recalculateRewardPerBlockTest(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "recalculateRewardPerBlockTest(uint256,uint256,uint256)"(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recalculateRewardUsingEpochRewardAmountTest(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "recalculateRewardUsingEpochRewardAmountTest(uint256)"(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  recalculateRewardPerBlockTest(
    _epochRewardAmount: BigNumberish,
    _blocksPerMin: BigNumberish,
    _epochLengthInDays: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "recalculateRewardPerBlockTest(uint256,uint256,uint256)"(
    _epochRewardAmount: BigNumberish,
    _blocksPerMin: BigNumberish,
    _epochLengthInDays: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recalculateRewardUsingEpochRewardAmountTest(
    _epochRewardAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "recalculateRewardUsingEpochRewardAmountTest(uint256)"(
    _epochRewardAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    recalculateRewardPerBlockTest(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "recalculateRewardPerBlockTest(uint256,uint256,uint256)"(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recalculateRewardUsingEpochRewardAmountTest(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "recalculateRewardUsingEpochRewardAmountTest(uint256)"(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    recalculateRewardPerBlockTest(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "recalculateRewardPerBlockTest(uint256,uint256,uint256)"(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recalculateRewardUsingEpochRewardAmountTest(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "recalculateRewardUsingEpochRewardAmountTest(uint256)"(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    recalculateRewardPerBlockTest(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "recalculateRewardPerBlockTest(uint256,uint256,uint256)"(
      _epochRewardAmount: BigNumberish,
      _blocksPerMin: BigNumberish,
      _epochLengthInDays: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recalculateRewardUsingEpochRewardAmountTest(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "recalculateRewardUsingEpochRewardAmountTest(uint256)"(
      _epochRewardAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
